### ISSUE TITLE
Cut new gem release

### ISSUE THREAD

**Issue by allaire** [seuros/capistrano-inspeqtor#2]
Hi @seuros 

Can you cut a new gem release? Currently have to point to Github to have a working version with latest Capistrano.

Thanks!

**Comment by seuros** [comment]
The current version support it.

**Comment by allaire** [comment]
not on rubygems

**Comment by seuros** [comment]
I'm sorry

**Comment by allaire** [comment]
:smile: No problem, thanks for your work!
