### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by allaire** [seuros/capistrano-inspeqtor#3]
Getting `8fcec/lib/capistrano/tasks/inspeqtor.cap:9:in `block in <top (required)>': undefined method `before' for main:Object (NoMethodError)`

**Comment by allaire** [comment]
This is because rails/bundler tries to `require` the file on app boot.

We have to either do like you did with cap's sidekiq: https://github.com/seuros/capistrano-sidekiq/tree/master/lib/capistrano

or add in the gemfile: `gem "capistrano-inspeqtor", require: false`

**Comment by seuros** [comment]
Thanks
